config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'diagnosis', to: 'welcome#diagnosis'
  get 'traffic_accident', to: 'welcome#traffic_accident'
  get 'recruitment', to: 'welcome#recruitment'
  get 'about', to: 'welcome#about'
  get 'bruise', to: 'welcome#bruise'
  get 'muscle', to: 'welcome#muscle'
  get 'sleeping', to: 'welcome#sleeping'
  get 'lumbago', to: 'welcome#lumbago'
  get 'pain_shoulder', to: 'welcome#pain_shoulder'
  get 'knee_pain', to: 'welcome#knee_pain'
  get 'back_pain', to: 'welcome#back_pain'
  get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
  get 'tenosynovitis', to: 'welcome#tenosynovitis'
  get 'hallux_valgus', to: 'welcome#hallux_valgus'
  get 'flat_foot', to: 'welcome#flat_foot'
  get 'posture', to: 'welcome#posture'

  resources :blogs
  resources :reviews
  resources :notifications

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }

  namespace :niconico do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :sugawara do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :admin do
    root to: "users#index"

    resources :users
    resources :blogs do
      collection do
        post :upload_image
      end
    end
    resources :reviews do
      collection do
        post :upload_image
      end
    end
    resources :notifications do
      collection do
        post :upload_image
      end
    end

    get '/sitemap.xml.gz' => redirect('http://karadasenmon.site/sitemap.xml.gz')
  end
end

app/controllers/niconico/base_controller.rb
class Niconico::BaseController < ApplicationController
  layout 'niconico'
end

app/controllers/niconico/blogs_controller.rb
class Niconico::BlogsController < Niconico::BaseController
  before_action :set_blog, only: [:show]

  def index
    @blogs = Blog.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/niconico/notifications_controller.rb
class Niconico::NotificationsController < Niconico::BaseController
  before_action :set_notification, only: [:show]

  def show
  end

  private
  def set_notification
    @notification = Notification.find(params[:id])
  end
end

app/controllers/niconico/reviews_controller.rb
class Niconico::ReviewsController < Niconico::BaseController
  before_action :set_review, only: [:show]

  def index
    @reviews = Review.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/niconico/welcome_controller.rb
class Niconico::WelcomeController < Niconico::BaseController

  def index
    @notifications = Notification.published.order(created_at: :desc).limit(50)
  end

  def diagnosis
  end

  def traffic_accident
  end

  def recruitment
  end

  def about
  end

  def bruise
  end

  def muscle
  end

  def sleeping
  end

  def lumbago
  end

  def pain_shoulder
  end

  def knee_pain
  end

  def back_pain
  end

  def stiff_shoulder
  end

  def tenosynovitis
  end

  def hallux_valgus
  end

  def flat_foot
  end

  def posture
  end
end

app/controllers/sugawara/welcome_controller.rb
class Sugawara::WelcomeController < Sugawara::BaseController

  def index
    @notifications = Notification.published.order(created_at: :desc).limit(50)
  end

  def diagnosis
  end

  def traffic_accident
  end

  def recruitment
  end

  def about
  end

  def bruise
  end

  def muscle
  end

  def sleeping
  end

  def lumbago
  end

  def pain_shoulder
  end

  def knee_pain
  end

  def back_pain
  end

  def stiff_shoulder
  end

  def tenosynovitis
  end

  def hallux_valgus
  end

  def flat_foot
  end

  def posture
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @notifications = Notification.published.order(created_at: :desc).limit(50)
  end

  def diagnosis
  end

  def traffic_accident
  end

  def recruitment
  end

  def about
  end

  def bruise
  end

  def muscle
  end

  def sleeping
  end

  def lumbago
  end

  def pain_shoulder
  end

  def knee_pain
  end

  def back_pain
  end

  def stiff_shoulder
  end

  def tenosynovitis
  end

  def hallux_valgus
  end

  def flat_foot
  end

  def posture
  end
end

app/views/niconico/welcome/about.html.erb
<div id="about">

  <div class="container top-image">
    <div class="row top-image-layer">
      <h2 class="top-image-title">当院のご案内</h2>
      <p class="title-en">ABOUT</p>
    </div>
  </div>

  <div id="introduction">
    <div class="container">
      <div class="row">
        <h2 class="grayhead">代表挨拶</h2>
        <div class="col-md-4 col-sm-4 col-xs-12 col-md-push-8"><%= image_tag 'daihyo-prof.png' %></div>
        <div class="col-md-8 col-sm-8 col-xs-12 col-md-pull-4 wow slideInLeft">
          <p>みなさん、こんにちは。にこにこグループ代表の菅原照太と申します。<br>
            私たち、にこにこＧＲＯＵＰは、整骨院事業を柱に、鍼灸院・デイサービス・訪問マッサージ・巻き爪ケア事業・トレーナー派遣事業など、地域の皆様の「生涯健康」「脱介護」を目標とし、健康産業に参入しております。 整骨・鍼灸・訪問マッサージ部門は、主に地域の皆様から、痛みの治療や健康維持、スポーツや仕事でのケガ、及び交通事故治療など、幅広くご利用頂いております。<br/>
            デイサービス・巻き爪ケア部門は、介護予防・転倒予防の観点から主に高齢者の方々を中心にご利用頂いております。
            トレーナー派遣事業についてはＪ３のプロサッカーチーム「ブラウブリッツ秋田」と提携をしており、選手への怪我の治療やユース年代への試合帯同及びサッカー大会でのメデイカルサポート、大学サッカーチームでのトレーナーサポート、秋田県選抜国体少年サッカーのトレーナーなど幅広い分野で活動しております。 また、スポーツトレーナーを目指す学生を応援しておりますので、毎年のように学生インターンの受け入れも積極的に行っております。<br/>
            このように弊社関連部門を通じて地域の皆様が生涯健康でありますよう微力ながら応援させていただきたいと思っております。
            今後ともどうぞよろしくお願いいたします。</p>
          <h3 class="bluebar">経歴</h3>
          <p>柔道整復師<br>足爪矯正士<br>JATAC認定アスレチックトレーナー<br>(一社)キネシオテーピング協会東北支部指導員<br>KOBA式体幹バランストレーニングマスターライセンス（S級）（サッカー専門ライセンス）</p>
        </div>
      </div>
    </div>
  </div>

  <div id="trainer-tie-up">
    <div class="container">
      <div class="row">
        <h2 class="grayhead">トレーナー提携</h2>
        <div class="col-md-5 col-sm-5 col-xs-12"><%= image_tag 'team-logo.jpg' %></div>
        <p class="col-md-7 col-sm-7 col-xs-12 wow slideInRight">にこにこグループ整骨院では、サッカーＪ３ブラウブリッツ秋田とメディカル部門で提携をしております。
          その関係からブラウブリッツ秋田ユース・Ｊｒユースへは当グループ整骨院からトレーナーが派遣されております。
          もちろんトップチームのＪリーガーも多数来院されますのでチームのトレーナーや医療機関との情報共有も常に行っております。
        </p>
      </div>
    </div>
  </div>

  <div id="image-slider">
    <div><%= image_tag 'gallery-1.jpg' %></div>
    <div><%= image_tag 'gallery-2.jpg' %></div>
    <div><%= image_tag 'gallery-3.jpg' %></div>
    <div><%= image_tag 'gallery-4.jpg' %></div>
    <div><%= image_tag 'gallery-5.jpg' %></div>
    <div><%= image_tag 'gallery-6.jpg' %></div>
    <div><%= image_tag 'gallery-7.jpg' %></div>
  </div>

  <div id="trainer-dispatch">
    <div class="layer-transparent">
      <div class="container">
        <h2 class="whitehead">トレーナー派遣</h2>
        <p class="wow slideInLeft">にこにこグループ整骨院ではトレーナー派遣及び講演、セミナーなどを受け付けております。<br>
          料金や内容など詳細につきましてはお近くの【にこにこグループ整骨院】までお問い合わせください。<br><br>
          ≪これまでの実績≫<br>
          ・トレーナー派遣<br>
          サッカースクール<br>
          大学サッカーチーム<br>
          サッカーフェステイバルトレーナーブース<br>
          秋田県選抜国体少年サッカー<br>
          ＢＢトップチーム合宿<br>
          ＢＢユース<br>
          ＢＢＪｒユース<br>
          Ｊドリームストレーナー<br><br>
          ・講演及びセミナー<br>
          ブラウブリッツ秋田主催の栄養セミナー・ストレッチ指導・スポーツ現場での応急処置<br>
          スポーツ少年団主催のテーピングセミナー<br>
          Ｊ３リーグ試合前のストレッチイベント<br>
          クラブチーム選手への体幹トレーニング指導<br>
          ＢＢユースへのトレーニング指導<br>
        </p>
      </div>
    </div>
  </div>

  <div id="links">
    <div class="container">
      <h2 class="grayhead">外部リンク</h2>
      <div class="row">
        <%= link_to "http://akitamakitume.com/", class: "link-item col-md-4 col-sm-4 col-xs-6" do %>
          <%= image_tag 'akita-makitume.png' %>
          <p>秋田院・大曲院</p>
        <% end %>
        <%= link_to "http://shonanmakitume.com/", class: "link-item col-md-4 col-sm-4 col-xs-6" do %>
          <%= image_tag 'shonan-makitume.png' %>
          <p>茅ヶ崎院・大船院</p>
        <% end %>
        <%= link_to "http://www.2ko2.com/index.php", class: "link-item col-md-4 col-sm-4 col-xs-6" do %>
          <%= image_tag 'nikoniko-group.png' %>
          <p>にこにこGROUP</p>
        <% end %>
        <span class="clearfix"></span>
        <%= link_to "http://akitamakitume.jugem.jp/", class: "link-item col-md-4 col-sm-4 col-xs-6" do %>
          <%= image_tag 'jugem.png' %>
          <p>秋田巻き爪矯正院巻き爪情報</p>
        <% end %>
        <%= link_to "https://ameblo.jp/3049akimasa/", class: "link-item col-md-4 col-sm-4 col-xs-6" do %>
          <%= image_tag 'ameba-blog.png' %>
          <p>湘南巻き爪矯正院ブログ</p>
        <% end %>
        <div class="link-item qr col-md-4 col-sm-4 col-xs-6">
          <%= image_tag 'qr-code.png' %>
          <p>モバイルサイト</p>
        </div>
      </div>
    </div>
  </div>

</div>

<script>
$(function() {
  $('#image-slider').slick({
    slidesToShow: 3,
    slidesToScroll: 1,
    autoplay: true,
    pauseOnHover: false,
    pauseOnDotsHover: false,
    infinite: true,
    autoplaySpeed: 0,
    cssEase: 'linear',
    speed: 5000,
    centerMode: true,
    centerPadding: '160px',
    arrows: false,

    responsive: [{
      breakpoint: 992,
        settings: {
          centerPadding: '40px',
        }
      }, {
      breakpoint: 640,
        settings: {
          centerPadding: '20px',
          slidesToShow: 2,
        }
      }
    ]
  });
});

new WOW({
  offset: 200,
  mobile: false,
}).init();
</script>

app/views/niconico/welcome/back_pain.html.erb
<div id="cases">
  <div class="container top-title">
    <h2 class="title-ja">ギックリ腰</h2>
  </div>

  <div id="explanation">
    <div class="container">
      <h2 class="grayhead">ギックリ腰とは</h2>
      <div class="col-md-5 col-sm-5 col-xs-12 col-md-push-7"><%= image_tag 'gikkuri.png' %></div>
      <p class="col-md-7 col-sm-7 col-xs-12 col-md-pull-5 wow slideInLeft">
        突然起こり、痛みで動けず大変な思いをするぎっくり腰は、ゴムで言うと古くなって伸縮性が無くなってしまったのと同じ状態に筋肉がなっているために起こります。<br/>使っている筋肉に対してきちんとケアが出来ていないため、柔軟性がなくなってしまっており、軽い動作で筋肉の表面の膜に傷がついてしまうのです。
      </p>
    </div>
  </div>

  <div id="how-to">
    <div class="container">
      <h2 class="grayhead">治療法</h2>
      <p>
        ギックリ腰にもいくつかの原因がありますので、患者様の状態に合わせてキネシオテープと言う特殊なテーピングを施し治療や、骨盤調整など最適な治療で早期快復を目指します。
      </p>
    </div>
  </div>
</div>

app/views/niconico/welcome/bruise.html.erb
<div id="cases">
  <div class="container top-title">
    <h2 class="title-ja">捻挫・打撲</h2>
  </div>

  <div id="explanation">
    <div class="container">
      <h2 class="grayhead">捻挫・打撲とは</h2>
      <div class="col-md-5 col-sm-5 col-xs-12 col-md-push-7"><%= image_tag 'kega-thumb.jpg' %></div>
      <p class="col-md-7 col-sm-7 col-xs-12 col-md-pull-5 wow slideInLeft">
        捻挫とは、スポーツ中のアクシデントや日常生活で転倒したときなどに、関節に運動範囲以上の負荷がかかったときに起きる外傷です。手首や足首などの関節がねじれることで、ときには骨や靱帯が傷つき、部分的に切れてしまうこともあります。<br/>
        打撲は、転倒や何かにぶつかるなどした場合に起きる組織損傷、言わゆる「打ち身」のことです。多くのケースでは傷口はありません。 頭部の打撲の場合で10～20分から数時間のうちに意識障害や手足に麻痺が見られる場合は「頭蓋内出血」の疑いがあります。少しでも吐き気や頭痛があれば、すぐに医療機関へ連絡する必要があります。<br/>
        胸部を打撲し、深呼吸などで強い痛みを感じれば「肋骨骨折」や「胸部骨折」の可能性があります。
      </p>
    </div>
  </div>

  <div id="how-to">
    <div class="container">
      <h2 class="grayhead">治療法</h2>
      <p>
        捻挫の多くは軽度のものですが、正しい処置をしなかったために重症化してしまうケースもあります。軽度の捻挫には、「スポーツ障害の対処法」でも紹介した※「RICE」が効果的です。「RICE」は手足などの軽度の打撲にも有効ですが、「打撲の症状」でご紹介したような危険性があるときは、医療機関での受診をおすすめします。また脱臼を起こした場合には、患部を固定して冷やしたまま、早めに専門医、接骨院、整形外科に行って診療してもらいましょう。治療を中断したり、固定期間が不足したりすると、ごくわずかな力が加わっただけでも簡単に脱臼を繰り返す場合がありますので、治療にはじっくり取り組みましょう。
      </p>
    </div>
  </div>
</div>

app/views/niconico/welcome/diagnosis.html.erb
<div id="diagnosis">

  <div class="container top-image">
    <div class="row top-image-layer">
      <h2 class="top-image-title">診療案内</h2>
      <p class="title-en">DIAGNOSIS</p>
    </div>
  </div>

  <div id="first-time">
    <div class="container">
      <h2 class="grayhead">初めての方へ</h2>
      <p>骨折・脱臼・肉離れ・捻挫・ギックリ腰・突き指・巻き爪・ムチウチ・寝違え、打撲・肩こり・腰痛・坐骨神経痛・交通事故治療‥など、中には保険治療対象外のものもありますが、自費治療として治療は行えますので、お身体に不調を感じたらお問い合わせ下さい。</p>
      <div class="treatments">
        <ul>
          <li class="treatment"><%= link_to niconico_bruise_path, type: :buton do %><span>捻挫・打撲</span><% end %></li>
          <li class="treatment"><%= link_to niconico_muscle_path, type: :buton do %><span>肉離れ</span><% end %></li>
          <li class="treatment"><%= link_to niconico_sleeping_path, type: :buton do %><span>寝違え</span><% end %></li>
          <li class="treatment"><%= link_to niconico_lumbago_path, type: :buton do %><span>腰痛</span><% end %></li>
          <li class="treatment"><%= link_to niconico_pain_shoulder_path, type: :buton do %><span>五十肩</span><% end %></li>
          <li class="treatment"><%= link_to niconico_knee_pain_path, type: :buton do %><span>ひざ痛</span><% end %></li>
          <li class="treatment"><%= link_to niconico_back_pain_path, type: :buton do %><span>ギックリ腰</span><% end %></li>
          <li class="treatment"><%= link_to niconico_stiff_shoulder_path, type: :buton do %><span>肩こり</span><% end %></li>
          <li class="treatment"><%= link_to niconico_tenosynovitis_path, type: :buton do %><span>腱鞘炎</span><% end %></li>
          <li class="treatment"><%= link_to niconico_hallux_valgus_path, type: :buton do %><span>外反母趾</span><% end %></li>
          <li class="treatment"><%= link_to niconico_flat_foot_path, type: :buton do %><span>扁平足</span><% end %></li>
          <li class="treatment"><%= link_to niconico_posture_path, type: :buton do %><span>姿勢の崩れ</span><% end %></li>
        </ul>
      </div>

      <div class="button-layer">
        <%= link_to "#footer", class: "reserv-access-button" do %>ご予約・アクセス<% end %>
      </div>
    </div>
  </div>

  <div id="time-table">
    <div class="container">
      <h2 class="grayhead">診療受付時間</h2>

      <table>
        <thead>
          <tr>
            <th class="col-md-4 col-sm-4 col-xs-5">にこにこ整骨院</th>
            <td class="col-md-4 col-sm-4 col-xs-4">月〜金</td>
            <td class="col-md-3 col-sm-3 col-xs-3">土・日</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th class="col-md-4 col-sm-4 col-xs-5">午前の部</th>
            <td class="col-md-4 col-sm-4 col-xs-4">8:30~11:30</td>
            <td class="col-md-3 col-sm-3 col-xs-3">✕</td>
          </tr>

          <tr>
            <th class="col-md-4 col-sm-4 col-xs-5">午後の部</th>
            <td class="col-md-4 col-sm-4 col-xs-4">14:30〜18:30</td>
            <td class="col-md-3 col-sm-3 col-xs-3">✕</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div id="price">
    <div class="container">
      <h2 class="grayhead">料金のご案内</h2>
      <h3 class="bluebar">交通事故治療の場合</h3>
      <table>
        <tr>
          <th>初診</th>
          <td>0円</td>
        </tr>
        <tr>
          <th>2回目以降</th>
          <td>0円</td>
        </tr>
      </table>

      <h3 class="bluebar">訪問マッサージの場合</h3>
      <table>
        <tr>
          <th>健康保険適用1割負担の方</th>
          <td>300~600円/回</td>
        </tr>
        <tr>
          <th>身体障害者手帳をお持ちの方</th>
          <td>0円</td>
        </tr>
      </table>

      <h3 class="bluebar">その他の治療メニュー</h3>
      <table>
        <tr>
          <th>筋肉調整</th>
          <td>300~1,000円</td>
        </tr>
        <tr>
          <th>骨盤調整</th>
          <td>3,240円</td>
        </tr>
        <tr>
          <th>肩こり調整</th>
          <td>2,160円</td>
        </tr>
        <tr>
          <th>外反母趾治療</th>
          <td>1,000〜2,000円</td>
        </tr>
        <tr>
          <th>巻き爪治療</th>
          <td>5,400~6,480円/指</td>
        </tr>
        <tr>
          <th>鍼治療</th>
          <td>100円/本</td>
        </tr>
        <tr>
          <th>足ツボ</th>
          <td>500円</td>
        </tr>
        <tr>
          <th>超音波治療</th>
          <td>500円</td>
        </tr>
        <tr>
          <th>脳ツボ</th>
          <td>500円</td>
        </tr>
        <tr>
          <th>レーザー治療</th>
          <td>0円</td>
        </tr>
        <tr>
          <th>エコー画像装置</th>
          <td>0円</td>
        </tr>
      </table>
      <p class="red-text">※店舗により取り扱いのないメニューもございます。</p>

      <div class="button-layer">
        <%= link_to "#footer", class: "reserv-access-button" do %>ご予約・アクセス<% end %>
      </div>
    </div>
  </div>

  <div id="flow-of-treatment">
    <div class="container">
      <h2 class="grayhead">施術の流れ</h2>
      <div class="flow-chart">
        <div class="steps">
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">1.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">問診・状態確認</p>
              <p>身体の不調な箇所や日頃の生活習慣、痛みなどをお伺いして症状の根本原因を見極めます。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">2.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">症状・治療方針の説明</p>
              <p>保険適応の治療や自費治療まで、患者様の症状に合った治療方針や治療期間をご提案させて頂きます。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">3.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">施術</p>
              <p>その場しのぎの施術でなく、「根本改善」「早期回復」を目的とした治療を行います。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">4.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">状態確認・日常生活のアドバイス</p>
              <p>施術前との状態を比べて効果を実感して頂いたうえで、症状改善に向けて日常生活で気をつけて頂きたいことをご紹介します。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">5.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">次回予約・お会計</p>
              <p>お帰りの際は次回ご予約も承ります。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="visit-treatment">
    <div class="container">
      <h2 class="grayhead">訪問マッサージ</h2>
      <h3>対象となる方</h3>
      <p>歩行が困難な方、歩行介助が必要な方、脳梗塞等の後遺症で手や足にマヒがある方、退院後もリハビリが必要な方、等。</p>
      <p>マッサージによってねたきり防止、関節拘縮の予防、現存機能の維持、床ずれ予防、血液リンパの循環改善、むくみの改善、筋肉痛の緩和、などが期待できます。</p>

      <h3>ご利用までの流れ</h3>
      <div class="flow-chart">
        <div class="steps">
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">1.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">お問い合わせ窓口に、お電話にてご確認ください。</p>
              <p>まずはお電話（<a href="tel:0187637220">0187-63-7220</a>）にてお問い合わせ下さい。内容を詳しくご説明させて頂きます。また、訪問範囲には制限があります。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">2.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">同意書にてお申し込み</p>
              <p>マッサージをご希望の場合は担当者が必要書類（同意書）を持ってご自宅までお伺いします。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">3.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">マッサージ開始</p>
              <p>国家資格を持った専門マッサージ師がご自宅までお伺いし、在宅マッサージを行います（健康保険適用）。</p>
            </div>
          </div>
          <div class="step row">
            <div class="number col-md-1 col-sm-1 col-xs-2">4.</div>
            <div class="content col-md-11 col-sm-11 col-xs-10">
              <p class="title">定期訪問</p>
              <p>週1～3回程度、患者様のご自宅までお伺いし、マッサージを行います。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="feature">
    <div class="layer-transparent">
      <div class="container">
        <h2 class="grayhead">患者様一人ひとりに寄り添った治療を</h2>
        <p class="wow slideInLeft">当グループ整骨院では初診時の聞き取り（問診）を大切にしております。<br>
        そのうえで患者様にあった治療方針や治療期間をご提案させて頂いております。
        特に根拠のある説明を大切にしておりますので、成長期におけるお子様のスポーツ障害などには超音波画像装置を用いご家族様を前に説明させて頂いております。<br>
        必要に応じて整形外科など医療機関をご紹介しております。</p>
      </div>
    </div>
  </div>
</div>

<script>
new WOW({
  offset: 200,
  mobile: false,
}).init();
</script>

app/views/niconico/welcome/flat_foot.html.erb
<div id="cases">
  <div class="container top-title">
    <h2 class="title-ja">扁平足</h2>
  </div>

  <div id="explanation">
    <div class="container">
      <h2 class="grayhead">扁平足とは</h2>
      <div class="col-md-5 col-sm-5 col-xs-12 col-md-push-7"><%= image_tag 'henpesoku.jpg' %></div>
      <p class="col-md-7 col-sm-7 col-xs-12 col-md-pull-5 wow slideInLeft">
        扁平足とは足裏のアーチ構造が崩れ、土踏まずがなくなった状態のことです。ただちに歩行に悪影響が出ることありませんが、足に負担がかかりやすくなり、足が疲れやすくなって長時間の歩行が困難になる恐れがあります。<br/>
        女性であれば外反母趾になるリスクが上がったり、スポーツをされている方であれば、足底筋膜炎や膝の怪我にも繋がってきます。
      </p>
    </div>
  </div>

  <div id="how-to">
    <div class="container">
      <h2 class="grayhead">治療法</h2>
      <p>
        当院では必要であればフットプリンター等を用い足のバランス測定やインソールの作成、ストレッチ等を用いた可動域訓練を行いアーチ構造の矯正を行います。
      </p>
    </div>
  </div>
</div>