config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'diagnosis', to: 'welcome#diagnosis'
  get 'traffic_accident', to: 'welcome#traffic_accident'
  get 'recruitment', to: 'welcome#recruitment'
  get 'about', to: 'welcome#about'
  get 'bruise', to: 'welcome#bruise'
  get 'muscle', to: 'welcome#muscle'
  get 'sleeping', to: 'welcome#sleeping'
  get 'lumbago', to: 'welcome#lumbago'
  get 'pain_shoulder', to: 'welcome#pain_shoulder'
  get 'knee_pain', to: 'welcome#knee_pain'
  get 'back_pain', to: 'welcome#back_pain'
  get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
  get 'tenosynovitis', to: 'welcome#tenosynovitis'
  get 'hallux_valgus', to: 'welcome#hallux_valgus'
  get 'flat_foot', to: 'welcome#flat_foot'
  get 'posture', to: 'welcome#posture'

  resources :blogs
  resources :reviews
  resources :notifications

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }

  namespace :niconico do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :sugawara do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :admin do
    root to: "users#index"

    resources :users
    resources :blogs do
      collection do
        post :upload_image
      end
    end
    resources :reviews do
      collection do
        post :upload_image
      end
    end
    resources :notifications do
      collection do
        post :upload_image
      end
    end

    get '/sitemap.xml.gz' => redirect('http://karadasenmon.site/sitemap.xml.gz')
  end
end

app/views/shared/_admin_header.html.erb
<nav class='navbar navbar-fixed-top navbar-inverse' role='navigation'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed'
              data-toggle='collapse'
              data-target='#header-navbar-collapse'
              aria-expanded='false'>
        <span class='icon-bar icon-bar--top'></span>
        <span class='icon-bar icon-bar--middle'></span>
        <span class='icon-bar icon-bar--bottom'></span>
      </button>
    </div>

    <div class='collapse navbar-collapse' id='header-navbar-collapse'>
      <ul class='nav navbar-nav navbar-left'>
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            ユーザー
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'ユーザー一覧', admin_users_path %></li>
          </ul>
        </li>
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            お知らせ
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'お知らせ一覧', admin_notifications_path %></li>
          </ul>
        </li>
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            ブログ
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'ブログ一覧', admin_blogs_path %></li>
          </ul>
        </li>
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            患者様の声
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to '患者様の声一覧', admin_reviews_path %></li>
          </ul>
        </li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <li></li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_footer.html.erb
<div id="footer">
  <div id="clinics">
    <div class="container">
      <div class="row">
        <h2 class="grayhead">施術所のご案内</h2>

        <% if store_type == "default" %>
          <div class="clinic col-md-6 col-md-offset-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1535.0887252869818!2d140.1009575571055!3d39.690713979456156!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f8fc3a116faa707%3A0x805a876251b1ef16!2z44CSMDEwLTAwNjUg56eL55Sw55yM56eL55Sw5biC6Iyo5bO277yX5LiB55uu77yU4oiS77yS77yW!5e0!3m2!1sja!2sjp!4v1511833253532" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <table>
              <tr>
                <th>施術所</th>
                <td>にこにこ鍼灸整骨院</td>
              </tr>
              <tr>
                <th>アクセス</th>
                <td>秋田県秋田市茨島7-4-26</td>
              </tr>
              <tr>
                <th>予約・お問い合わせ</th>
                <td><a href="tel:0188747530">018-874-7530</a></td>
              </tr>
              <tr>
                <th>診療受付時間</th>
                <td><p>【月〜金】</p><p>8：30～12：00</p><p>15:00〜19:00</p></td>
              </tr>
              <tr>
                <th>定休日</th>
                <td>土曜日・日曜日</td>
              </tr>
            </table>
          </div>
        <% elsif store_type == "niconico" %>
          <div class="clinic col-md-6 col-md-offset-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1539.8626268003488!2d140.45778545710056!3d39.47553517948577!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f8fa14007194417%3A0xf795c134c981092!2z44CSMDE0LTAwMDUg56eL55Sw55yM5aSn5LuZ5biC6Iqx6aSo5p-z55S677yR4oiS77yT77yV!5e0!3m2!1sja!2sjp!4v1511833192361" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <table>
              <tr>
                <th>施術所</th>
                <td>にこにこ整骨院</td>
              </tr>
              <tr>
                <th>アクセス</th>
                <td>秋田県大仙市花館柳町1-35</td>
              </tr>
              <tr>
                <th>予約・お問い合わせ</th>
                <td><a href="tel:0187735280 ">0187-73-5280</a></td>
              </tr>
              <tr>
                <th>診療受付時間</th>
                <td><p>【月〜金】</p><p>8：00～11：30</p><p>14:30〜18:30</p></td>
              </tr>
              <tr>
                <th>定休日</th>
                <td>土曜日・日曜日</td>
              </tr>
            </table>
          </div>
        <% else %>
          <div class="clinic col-md-6 col-md-offset-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12320.845417332384!2d140.4757144!3d39.4645537!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb9bbfa36288564f!2z44CSMDE0LTAwMTQg56eL55Sw55yM5aSn5LuZ5biC5aSn5puy56aP5L2P55S677yW4oiS77yS77yQ!5e0!3m2!1sja!2sjp!4v1519019269599" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            <table>
              <tr>
                <th>施術所</th>
                <td>すがわら整骨院</td>
              </tr>
              <tr>
                <th>アクセス</th>
                <td>秋田県大仙市大曲福住町6-20</td>
              </tr>
              <tr>
                <th>予約・お問い合わせ</th>
                <td><a href="tel:0187638682">0187-63-8682</a></td>
              </tr>
              <tr>
                <th>診療受付時間</th>
                <td><p>【月〜金】</p><p>8：30～12：00</p><p>15:00〜19:00</p><p>【土】</p><p>8：30～12：00</p></td>
              </tr>
              <tr>
                <th>定休日</th>
                <td>日曜日・祝日</td>
              </tr>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div id="sitemap">
    <div class="container">

      <% if store_type == "default" %>
        <ul>
          <li class="category"><%= link_to root_path do %>HOME<% end %></li>
          <li class="category"><%= link_to diagnosis_path do %>診療案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'first-time') do %>はじめての方へ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'time-table') do %>診療受付時間<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'price') do %>料金のご案内<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'flow-of-treatment') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'visit-treatment') do %>訪問マッサージ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'feature') do %>患者様一人ひとりに寄り添った治療を<% end %>
          </li>
          <li class="category"><%= link_to traffic_accident_path do %>交通事故治療<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'price') do %>治療料金<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'flow-of-accident') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'suggest-treatment') do %>怪我の自覚症状が無くても診察を<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'car-insurance') do %>自賠責保険<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'consolation-money') do %>治療費と慰謝料<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'case-of-uninsured') do %>保険が適用されないケース<% end %>
          </li>
          <li class="category"><%= link_to about_path do %>当院のご案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'introduction') do %>代表挨拶<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-tie-up') do %>トレーナー提携<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-dispatch') do %>トレーナー派遣<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'links') do %>外部リンク<% end %>
          </li>
          <li class="category"><%= link_to reviews_path do %>患者様の声<% end %></li>
          <li class="category"><%= link_to blogs_path do %>ブログ<% end %></li>
          <li class="sub-category"><%= link_to recruitment_path do %>採用情報<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'staff-recruitment') do %>スタッフ募集<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'recruitment-contents') do %>求人内容<% end %>
          </li>
        </ul>
      <% elsif store_type == "niconico" %>
        <ul>
          <li class="category"><%= link_to niconico_root_path do %>HOME<% end %></li>
          <li class="category"><%= link_to niconico_diagnosis_path do %>診療案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'first-time') do %>はじめての方へ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'time-table') do %>診療受付時間<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'price') do %>料金のご案内<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'flow-of-treatment') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'visit-treatment') do %>訪問マッサージ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'feature') do %>患者様一人ひとりに寄り添った治療を<% end %>
          </li>
          <li class="category"><%= link_to niconico_traffic_accident_path do %>交通事故治療<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'price') do %>治療料金<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'flow-of-accident') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'suggest-treatment') do %>怪我の自覚症状が無くても診察を<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'car-insurance') do %>自賠責保険<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'consolation-money') do %>治療費と慰謝料<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'case-of-uninsured') do %>保険が適用されないケース<% end %>
          </li>
          <li class="category"><%= link_to niconico_about_path do %>当院のご案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'introduction') do %>代表挨拶<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-tie-up') do %>トレーナー提携<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-dispatch') do %>トレーナー派遣<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'links') do %>外部リンク<% end %>
          </li>
          <li class="category"><%= link_to niconico_reviews_path do %>患者様の声<% end %></li>
          <li class="category"><%= link_to niconico_blogs_path do %>ブログ<% end %></li>
          <li class="sub-category"><%= link_to recruitment_path do %>採用情報<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'staff-recruitment') do %>スタッフ募集<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'recruitment-contents') do %>求人内容<% end %>
          </li>
        </ul>
      <% else %>
        <ul>
          <li class="category"><%= link_to sugawara_root_path do %>HOME<% end %></li>
          <li class="category"><%= link_to sugawara_diagnosis_path do %>診療案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'first-time') do %>はじめての方へ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'time-table') do %>診療受付時間<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'price') do %>料金のご案内<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'flow-of-treatment') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'visit-treatment') do %>訪問マッサージ<% end %>
            <%= link_to url_for(controller: :welcome, action: :diagnosis, anchor: 'feature') do %>患者様一人ひとりに寄り添った治療を<% end %>
          </li>
          <li class="category"><%= link_to sugawara_traffic_accident_path do %>交通事故治療<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'price') do %>治療料金<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'flow-of-accident') do %>施術の流れ<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'suggest-treatment') do %>怪我の自覚症状が無くても診察を<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'car-insurance') do %>自賠責保険<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'consolation-money') do %>治療費と慰謝料<% end %>
            <%= link_to url_for(controller: :welcome, action: :traffic_accident, anchor: 'case-of-uninsured') do %>保険が適用されないケース<% end %>
          </li>
          <li class="category"><%= link_to sugawara_about_path do %>当院のご案内<% end %></li>
          <li class="sub-category">
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'introduction') do %>代表挨拶<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-tie-up') do %>トレーナー提携<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'trainer-dispatch') do %>トレーナー派遣<% end %>
            <%= link_to url_for(controller: :welcome, action: :about, anchor: 'links') do %>外部リンク<% end %>
          </li>
          <li class="category"><%= link_to sugawara_reviews_path do %>患者様の声<% end %></li>
          <li class="category"><%= link_to sugawara_blogs_path do %>ブログ<% end %></li>
          <li class="sub-category"><%= link_to recruitment_path do %>採用情報<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'staff-recruitment') do %>スタッフ募集<% end %>
            <%= link_to url_for(controller: :welcome, action: :recruitment, anchor: 'recruitment-contents') do %>求人内容<% end %>
          </li>
        </ul>
      <% end %>

    </div>
  </div>

  <div id="copyright">
    <p>Copyright にこにこグループ整骨院  All Rights Reserved. 無断転載禁止</p>
  </div>
</div>

app/views/shared/_ga.html.erb
<% if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-111685502-1', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/shared/_header.html.erb
<div id="header">
  <div class="header-content">
    <div id="site-logo">
      <% if store_type == "default" %>
        <%= link_to root_path, class: "link-to-root" do %>
          <%= image_tag 'logo_medium.png' %><h1>にこにこ鍼灸整骨院</h1>
        <% end %>
      <% elsif store_type == "niconico" %>
        <%= link_to niconico_root_path, class: "link-to-root" do %>
          <%= image_tag 'logo_medium.png' %><h1>にこにこ整骨院</h1>
        <% end %>
      <% else %>
        <%= link_to sugawara_root_path, class: "link-to-root" do %>
          <%= image_tag 'logo_medium.png' %><h1>すがわら整骨院</h1>
        <% end %>
      <% end %>

      <div class="store-menu-pc">
        <h3 class="store-title">口コミで評判！秋田県の整骨院</h3>
        <div class="store-items">
          <%= link_to root_path, class: "store-item" do %><p class="main">秋田市</p><p class="mini">茨島</p><% end %>
          <%= link_to niconico_root_path, class: "store-item" do %><p class="main">大仙市</p><p class="mini">花館</p><% end %>
          <%= link_to sugawara_root_path, class: "store-item" do %><p class="main">大仙市</p><p class="mini">大曲</p><% end %>
        </div>
      </div>

      <%= link_to "#footer", class: "link-to-access" do %><p class="reservation">お問い合わせ</p><p class="access">アクセス／店舗案内</p><% end %>
    </div>

    <nav>

      <% if store_type == "default" %>
        <ul>
          <li><%= link_to diagnosis_path do %>診療案内<span class="english">DIAGNOSIS</span><% end %></li>
          <li><%= link_to traffic_accident_path do %>交通事故治療<span class="english">TRAFFIC ACCIDENT</span><% end %></li>
          <li><%= link_to about_path do %>当院のご案内<span class="english">ABOUT</span><% end %></li>
          <li><%= link_to reviews_path do %>患者様の声<span class="english">REVIEWS</span><% end %></li>
          <li><%= link_to blogs_path do %>ブログ<span class="english">BLOG</span><% end %></li>
          <li><%= link_to recruitment_path do %>採用情報<span class="english">RECRUITMENT</span><% end %></li>
          <li><%= link_to "#footer", id: "access-btn" do %>ご予約・アクセス<% end %></li>
        </ul>
      <% elsif store_type == "niconico" %>
        <ul>
          <li><%= link_to niconico_diagnosis_path do %>診療案内<span class="english">DIAGNOSIS</span><% end %></li>
          <li><%= link_to niconico_traffic_accident_path do %>交通事故治療<span class="english">TRAFFIC ACCIDENT</span><% end %></li>
          <li><%= link_to niconico_about_path do %>当院のご案内<span class="english">ABOUT</span><% end %></li>
          <li><%= link_to niconico_reviews_path do %>患者様の声<span class="english">REVIEWS</span><% end %></li>
          <li><%= link_to niconico_blogs_path do %>ブログ<span class="english">BLOG</span><% end %></li>
          <li><%= link_to niconico_recruitment_path do %>採用情報<span class="english">RECRUITMENT</span><% end %></li>
          <li><%= link_to "#footer", id: "access-btn" do %>ご予約・アクセス<% end %></li>
        </ul>
      <% else %>
        <ul>
          <li><%= link_to sugawara_diagnosis_path do %>診療案内<span class="english">DIAGNOSIS</span><% end %></li>
          <li><%= link_to sugawara_traffic_accident_path do %>交通事故治療<span class="english">TRAFFIC ACCIDENT</span><% end %></li>
          <li><%= link_to sugawara_about_path do %>当院のご案内<span class="english">ABOUT</span><% end %></li>
          <li><%= link_to sugawara_reviews_path do %>患者様の声<span class="english">REVIEWS</span><% end %></li>
          <li><%= link_to sugawara_blogs_path do %>ブログ<span class="english">BLOG</span><% end %></li>
          <li><%= link_to sugawara_recruitment_path do %>採用情報<span class="english">RECRUITMENT</span><% end %></li>
          <li><%= link_to "#footer", id: "access-btn" do %>ご予約・アクセス<% end %></li>
        </ul>
      <% end %>

      <div class="nav_icon">
        <span class="nav-icon-bar"></span>
        <span class="nav-icon-bar"></span>
        <span class="nav-icon-bar"></span>
        <span class="nav-icon-text">MENU</span>
      </div>
    </nav>
  </div>
</div>

<div class="store-menu-mb">
  <h3 class="store-title">口コミで評判！秋田県の整骨院</h3>
  <div class="store-items">
    <%= link_to root_path, class: "store-item" do %><p class="main">秋田市</p><p class="mini">茨島</p><% end %>
    <%= link_to niconico_root_path, class: "store-item" do %><p class="main">大仙市</p><p class="mini">花館</p><% end %>
    <%= link_to sugawara_root_path, class: "store-item" do %><p class="main">大仙市</p><p class="mini">大曲</p><% end %>
  </div>
</div>