config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'diagnosis', to: 'welcome#diagnosis'
  get 'traffic_accident', to: 'welcome#traffic_accident'
  get 'recruitment', to: 'welcome#recruitment'
  get 'about', to: 'welcome#about'
  get 'bruise', to: 'welcome#bruise'
  get 'muscle', to: 'welcome#muscle'
  get 'sleeping', to: 'welcome#sleeping'
  get 'lumbago', to: 'welcome#lumbago'
  get 'pain_shoulder', to: 'welcome#pain_shoulder'
  get 'knee_pain', to: 'welcome#knee_pain'
  get 'back_pain', to: 'welcome#back_pain'
  get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
  get 'tenosynovitis', to: 'welcome#tenosynovitis'
  get 'hallux_valgus', to: 'welcome#hallux_valgus'
  get 'flat_foot', to: 'welcome#flat_foot'
  get 'posture', to: 'welcome#posture'

  resources :blogs
  resources :reviews
  resources :notifications

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    unlocks: "users/unlocks",
    confirmations: "users/confirmations"
  }

  namespace :niconico do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :sugawara do
    root 'welcome#index'

    get 'diagnosis', to: 'welcome#diagnosis'
    get 'traffic_accident', to: 'welcome#traffic_accident'
    get 'recruitment', to: 'welcome#recruitment'
    get 'about', to: 'welcome#about'
    get 'bruise', to: 'welcome#bruise'
    get 'muscle', to: 'welcome#muscle'
    get 'sleeping', to: 'welcome#sleeping'
    get 'lumbago', to: 'welcome#lumbago'
    get 'pain_shoulder', to: 'welcome#pain_shoulder'
    get 'knee_pain', to: 'welcome#knee_pain'
    get 'back_pain', to: 'welcome#back_pain'
    get 'stiff_shoulder', to: 'welcome#stiff_shoulder'
    get 'tenosynovitis', to: 'welcome#tenosynovitis'
    get 'hallux_valgus', to: 'welcome#hallux_valgus'
    get 'flat_foot', to: 'welcome#flat_foot'
    get 'posture', to: 'welcome#posture'

    resources :blogs
    resources :reviews
    resources :notifications
  end

  namespace :admin do
    root to: "users#index"

    resources :users
    resources :blogs do
      collection do
        post :upload_image
      end
    end
    resources :reviews do
      collection do
        post :upload_image
      end
    end
    resources :notifications do
      collection do
        post :upload_image
      end
    end

    get '/sitemap.xml.gz' => redirect('http://karadasenmon.site/sitemap.xml.gz')
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::BaseController
  skip_before_filter :verify_authenticity_token
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def show
    if @review.published?
      redirect_to review_path(@review)
    end
  end

  def new
    @review = Review.new
  end

  def create
    review = Review.create()
    redirect_to edit_admin_review_path(review.id)
  end

  def edit
  end

  def update
    @review.update(review_params)
    if params["commit"] == "プレビューを見る"
      redirect_to admin_review_path(params[:id])
    elsif params["commit"] == "公開された記事を見る"
      redirect_to :controller => "reviews", :action => "show", id: params[:id]
    elsif request.xhr?
      render json: {
        ok: true
      }
    else
      redirect_to admin_reviews_path
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path
  end

  def upload_image
    if params[:file]
      FileUtils::mkdir_p(Rails.root.join("public/uploads/froala"))
      ext = File.extname(params[:file].original_filename)
      if IMAGE_EXT.include?(ext)
        file_name = "#{SecureRandom.urlsafe_base64}#{ext}"
        path = Rails.root.join("public/uploads/froala/", file_name)
        File.open(path, "wb") {|f| f.write(params[:file].read)}
        view_file = Rails.env.production? ? DOMAIN + "uploads/froala/" + file_name : "http://localhost:3000/" + "uploads/froala/" + file_name
        render :json => {:link => view_file}.to_json
      else
        render :text => {:link => nil}.to_json
      end
    else
      render :text => {:link => nil}.to_json
    end
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :status, :image)
  end
end

app/controllers/niconico/base_controller.rb
class Niconico::BaseController < ApplicationController
  layout 'niconico'
end

app/controllers/niconico/blogs_controller.rb
class Niconico::BlogsController < Niconico::BaseController
  before_action :set_blog, only: [:show]

  def index
    @blogs = Blog.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/niconico/notifications_controller.rb
class Niconico::NotificationsController < Niconico::BaseController
  before_action :set_notification, only: [:show]

  def show
  end

  private
  def set_notification
    @notification = Notification.find(params[:id])
  end
end

app/controllers/niconico/reviews_controller.rb
class Niconico::ReviewsController < Niconico::BaseController
  before_action :set_review, only: [:show]

  def index
    @reviews = Review.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/niconico/welcome_controller.rb
class Niconico::WelcomeController < Niconico::BaseController

  def index
    @notifications = Notification.published.order(created_at: :desc).limit(50)
  end

  def diagnosis
  end

  def traffic_accident
  end

  def recruitment
  end

  def about
  end

  def bruise
  end

  def muscle
  end

  def sleeping
  end

  def lumbago
  end

  def pain_shoulder
  end

  def knee_pain
  end

  def back_pain
  end

  def stiff_shoulder
  end

  def tenosynovitis
  end

  def hallux_valgus
  end

  def flat_foot
  end

  def posture
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show]

  def index
    @reviews = Review.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/sugawara/reviews_controller.rb
class Sugawara::ReviewsController < Sugawara::BaseController
  before_action :set_review, only: [:show]

  def index
    @reviews = Review.published.order(created_at: :desc).paginate(page: params[:page], per_page: 18)
  end

  def show
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end
end

app/views/niconico/reviews/index.html.erb
<div id="review-index">

  <div class="container top-title">
    <h2 class="title-ja">患者様の声</h2>
    <p class="title-en">REVIEWS</p>
  </div>

  <div class="reviews">
    <div class="container">

      <h2 class="bluebar">患者様の声一覧</h2>
      <% if @reviews.present? %>
        <ul>
          <% @reviews.each do |r| %>
            <li class="review">
              <%= link_to niconico_review_path(r.id) do %>
                <div class="review-thumb" style="background-image: url(<%= asset_path "hito_icon.png" %>)"></div>
                <div class="review-content">
                  <h3 class="review-title"><%= r.title.length > 26 ? r.title[0, 26] + "..." : r.title %></h3>
                  <p class="review-description"><%= strip_tags(r.content).length > 39 ? strip_tags(r.content)[0, 39] + "..." : strip_tags(r.content) %></p>
                  <p class="review-date"><%= r.updated_at.strftime("%Y/%m/%d") %></p>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="not-found">記事が見つかりませんでした。</p>
      <% end %>

      <%= will_paginate @reviews %>
    </div>
  </div>
</div>

app/views/niconico/reviews/show.html.erb
<div id="review-show">

  <div class="container top-title">
    <h2 class="title-ja">患者様の声</h2>
    <p class="title-en">REVIEWS</p>
  </div>

  <div class="review">
    <div class="container">
      <div class="review-title">
        <h1><%= @review.title %></h1>
      </div>

      <div class="review-date">
        <span class="cat-tag">患者様の声</span>
        <span class="date"><%= @review.updated_at.strftime("%Y/%m/%d")  %></span>
      </div>

      <% if !@review.image.blank? %>
        <div class='eyecatch'>
          <%= image_tag @review.image %>
        </div>
      <% end %>

      <div class="review-content">
        <%= @review.content.try(:html_safe) %>
      </div>

    </div>
  </div>
</div>